export const WORKFLOW_STATE_STORE = Symbol('WORKFLOW_STATE_STORE');

export const WORKFLOW_IDEMPOTENCY_STORE = Symbol('WORKFLOW_IDEMPOTENCY_STORE');

export const WORKFLOW_HISTORY_STORE = Symbol('WORKFLOW_HISTORY_STORE');

export const WORKFLOW_SIGNAL_STORE = Symbol('WORKFLOW_SIGNAL_STORE');

export const WORKFLOW_TRANSACTION_RUNNER = Symbol(
  'WORKFLOW_TRANSACTION_RUNNER',
);

export const WORKFLOW_RETRY_JITTER = Symbol('WORKFLOW_RETRY_JITTER');

export const WORKFLOW_RETRY_SCHEDULER = Symbol('WORKFLOW_RETRY_SCHEDULER');

export const WORKFLOW_METRICS = Symbol('WORKFLOW_METRICS');
