export const WORKFLOW_STATE_STORE = Symbol('WORKFLOW_STATE_STORE');

export const WORKFLOW_IDEMPOTENCY_STORE = Symbol('WORKFLOW_IDEMPOTENCY_STORE');

export const WORKFLOW_HISTORY_STORE = Symbol('WORKFLOW_HISTORY_STORE');

export const WORKFLOW_SIGNAL_STORE = Symbol('WORKFLOW_SIGNAL_STORE');
